### ISSUE TITLE
Dry-run mode for command

### ISSUE THREAD

**Issue by jmfayard** [lordcodes/turtle#114]
**Describe the problem**

Assuming I have a script that does a lot of git stuff, I would like to have a [dry run](https://en.wikipedia.org/wiki/Dry_run_(testing)) mode to check that my git syntax is correct before actually doing a git operation

**Describe your solution**

- add `fun GitCommands.dryRunMode()` 
- change `fun GitCommands.gitCommand()` so that it does `echo git command something` instead of `git command something` when dry run is enabled

**Checklist**

- [x] I've read the [guide for contributing](https://github.com/lordcodes/turtle/blob/master/CONTRIBUTING.md).
- [x] I've checked there are no other [open pull requests](https://github.com/lordcodes/turtle/pulls) for the feature.
- [x] I've checked there are no other [open issues](https://github.com/lordcodes/turtle/issues) for the same feature.

**Comment by lordcodes** [comment]
I'm not keen on a mutable command that actually alters how all the other commands work. I think I would probably instead offer an 'echo' command that can take a ShellScript as input or something along those lines.

I will admit this feels quite specific, the idea was that Turtle offers the core of running commands so that you don't need to duplicate all of that into every project and to then offer some commonly used commands. Then, design the API so that it is very easy to add your own commands via extensions.

I may be wrong, but to me this option feels quite specific so may just live best as an extension you include in your projects. If changes are needed to the API to allow an extension like this to be written, then I would agree those should be made as I think Turtle's API should be designed in a way that users can extend it as much as possible.

**Comment by jmfayard** [comment]
Many commands that either can take a long time to complete or can have potentially big side effects have a dry run flag.

That's the case for Gradle for example: running `./gradlew check` can take a long time.
But if I just want to check that the Gradle configuration is OK, running `gradle --dry-run check` is super fast.

> I feel like this 'dry-run' command feels quite specific 

What was too specific in my issue is to do that for `git` only. 
That actually makes sense for all commands.

> However, if changes are needed to the API to allow an extension like this to be written, then I would agree those should be made.

Yep, `com.lordcodes.turtle.ShellScript.runCommand()` would need to be modified so that instead of executing the command, it does something like 

`println("$ $command ${arguments.joinToString(" ")}`

**Comment by lordcodes** [comment]
That is a very fair argument.

**Comment by jmfayard** [comment]
No difference really. `println("ls src")` and `println(runCommand("echo", listOf("ls", "src")))` are exactly the same thing.

**Comment by jmfayard** [comment]
The difference would be that I can run my entire scripts and see the list of commands that would be executed, having as output something like a Bash script. And for that I just have to configure the dry run mode in one place, instead of modifying all my commands.

**Comment by lordcodes** [comment]
So you are suggesting, dry run would be a mutable mode that you enable and then all the following commands would run using it. There may be a way to build this into the API as an input argument `shellRun(dryRun = true)` or a different function `shellDryRun { ... }`.

**Comment by jmfayard** [comment]
Nice, thanks 👍
