### ISSUE TITLE
Inject ProcessBuilder/Process

### ISSUE THREAD

**Issue by stabla** [lordcodes/turtle#41]
**Describe the problem**
Hi, 

I would like to get a timer on a task. If a task is not ending after let's say 1 hour, could we shut down the process?

**Describe your solution**
It you have any idea on how we can do this, or if shellRun could returns a process id, let me know, I would really be happy to have such feature! And if I'm able to do that, I will do a PR!

**Comment by stabla** [comment]
Or is there a way to get the PID when executing ShellRun?

Thank you for your response

**Comment by lordcodes** [comment]
Within the `shellRun` block, each individual command you execute is a 'Process' therefore, the shell Process itself doesn't run for the duration of the shellRun block.

Therefore, I think you would just need to implement this yourself. The library is designed for quickly running simple shell commands to avoid all the ProcessBuilder boilerplate and collecting output for you.

I believe you should be able to add an extension on ShellScript, but you would need to then implement what is currently inside the 'command' function yourself to make the Process end after a timeout.

We could maybe consider encapsulating the contents of 'command' into an object so you could reuse it, but right now I think it would be hard to predict all the things different people may want to do.

**Comment by lordcodes** [comment]
Please be aware, I would like to keep the library as simple as possible and don't want to add various different customisations to it that individual people/use cases may need.

For example, I don't really want to add all the code for timing a process to the library. That can be implemented by consumers of the library.

**Comment by lordcodes** [comment]
I have been thinking about this and would like to explore injecting the ProcessBuilder/Process. I think to get much value we need to allow the Process to be started and passed in, or a configure lambda to be provided that can operate on the Process that gets started.

There are various things to explore:

* Whether it is possible to reuse the Process between commands or if each needs to use a new 'Process' instance.
* How best to inject it so that it can be used outside shellRun to do things like timing, killing after a timeout or at least accessing the PID.
* Making the API nice to use and readable.
